# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatteryInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_batteryInfo(object):
    def setupUi(self, batteryInfo):
        batteryInfo.setObjectName("batteryInfo")
        batteryInfo.resize(346, 448)
        self.Pb_OKBI = QtWidgets.QPushButton(batteryInfo)
        self.Pb_OKBI.setGeometry(QtCore.QRect(60, 390, 75, 23))
        self.Pb_OKBI.setObjectName("Pb_OKBI")
        self.Pb_CancelBI = QtWidgets.QPushButton(batteryInfo)
        self.Pb_CancelBI.setGeometry(QtCore.QRect(220, 390, 75, 23))
        self.Pb_CancelBI.setObjectName("Pb_CancelBI")
        self.sB_UnitBattery = QtWidgets.QSpinBox(batteryInfo)
        self.sB_UnitBattery.setGeometry(QtCore.QRect(180, 260, 91, 22))
        self.sB_UnitBattery.setObjectName("sB_UnitBattery")
        self.lE_BatteryNO = QtWidgets.QLineEdit(batteryInfo)
        self.lE_BatteryNO.setGeometry(QtCore.QRect(180, 220, 91, 20))
        self.lE_BatteryNO.setObjectName("lE_BatteryNO")
        self.sB_UnitBatteryPack = QtWidgets.QSpinBox(batteryInfo)
        self.sB_UnitBatteryPack.setGeometry(QtCore.QRect(180, 300, 91, 22))
        self.sB_UnitBatteryPack.setObjectName("sB_UnitBatteryPack")
        self.dSB_Battery_Area = QtWidgets.QSpinBox(batteryInfo)
        self.dSB_Battery_Area.setGeometry(QtCore.QRect(180, 340, 91, 22))
        self.dSB_Battery_Area.setObjectName("dSB_Battery_Area")
        self.l_BatteryInfo_R = QtWidgets.QLabel(batteryInfo)
        self.l_BatteryInfo_R.setGeometry(QtCore.QRect(120, 190, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(11)
        self.l_BatteryInfo_R.setFont(font)
        self.l_BatteryInfo_R.setObjectName("l_BatteryInfo_R")
        self.l_BatteryNO_2 = QtWidgets.QLabel(batteryInfo)
        self.l_BatteryNO_2.setGeometry(QtCore.QRect(50, 220, 81, 16))
        self.l_BatteryNO_2.setObjectName("l_BatteryNO_2")
        self.l_UnitBattery = QtWidgets.QLabel(batteryInfo)
        self.l_UnitBattery.setGeometry(QtCore.QRect(50, 260, 81, 16))
        self.l_UnitBattery.setObjectName("l_UnitBattery")
        self.l_UnitBatteryPack = QtWidgets.QLabel(batteryInfo)
        self.l_UnitBatteryPack.setGeometry(QtCore.QRect(50, 300, 81, 16))
        self.l_UnitBatteryPack.setObjectName("l_UnitBatteryPack")
        self.l__Battery_Area = QtWidgets.QLabel(batteryInfo)
        self.l__Battery_Area.setGeometry(QtCore.QRect(50, 340, 101, 16))
        self.l__Battery_Area.setObjectName("l__Battery_Area")
        self.l_BatteryUnit = QtWidgets.QLabel(batteryInfo)
        self.l_BatteryUnit.setGeometry(QtCore.QRect(80, 90, 131, 16))
        self.l_BatteryUnit.setObjectName("l_BatteryUnit")
        self.l_BatteryArea = QtWidgets.QLabel(batteryInfo)
        self.l_BatteryArea.setGeometry(QtCore.QRect(80, 150, 131, 16))
        self.l_BatteryArea.setObjectName("l_BatteryArea")
        self.l_BatteryInfo_S = QtWidgets.QLabel(batteryInfo)
        self.l_BatteryInfo_S.setGeometry(QtCore.QRect(110, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(11)
        self.l_BatteryInfo_S.setFont(font)
        self.l_BatteryInfo_S.setObjectName("l_BatteryInfo_S")
        self.l_BatteryNO = QtWidgets.QLabel(batteryInfo)
        self.l_BatteryNO.setGeometry(QtCore.QRect(80, 60, 131, 16))
        self.l_BatteryNO.setObjectName("l_BatteryNO")
        self.line_batteryInfo = QtWidgets.QFrame(batteryInfo)
        self.line_batteryInfo.setGeometry(QtCore.QRect(40, 170, 261, 16))
        self.line_batteryInfo.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_batteryInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_batteryInfo.setObjectName("line_batteryInfo")
        self.l_BatteryPack = QtWidgets.QLabel(batteryInfo)
        self.l_BatteryPack.setGeometry(QtCore.QRect(80, 120, 131, 16))
        self.l_BatteryPack.setObjectName("l_BatteryPack")

        self.retranslateUi(batteryInfo)
        self.Pb_CancelBI.clicked.connect(batteryInfo.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(batteryInfo)

    def retranslateUi(self, batteryInfo):
        _translate = QtCore.QCoreApplication.translate
        batteryInfo.setWindowTitle(_translate("batteryInfo", "电池信息设置"))
        self.Pb_OKBI.setText(_translate("batteryInfo", "确定修改"))
        self.Pb_CancelBI.setText(_translate("batteryInfo", "取消修改"))
        self.l_BatteryInfo_R.setText(_translate("batteryInfo", "修改电池信息"))
        self.l_BatteryNO_2.setText(_translate("batteryInfo", "电池编号："))
        self.l_UnitBattery.setText(_translate("batteryInfo", "单体电池节数："))
        self.l_UnitBatteryPack.setText(_translate("batteryInfo", "电池片数："))
        self.l__Battery_Area.setText(_translate("batteryInfo", "<html><head/><body><p>电池片面积(cm<span style=\" vertical-align:super;\">2</span>)：</p></body></html>"))
        self.l_BatteryUnit.setText(_translate("batteryInfo", "电池节数："))
        self.l_BatteryArea.setText(_translate("batteryInfo", "电池面积："))
        self.l_BatteryInfo_S.setText(_translate("batteryInfo", "当前电池信息"))
        self.l_BatteryNO.setText(_translate("batteryInfo", "电池编号："))
        self.l_BatteryPack.setText(_translate("batteryInfo", "电池片数："))
